# -*- coding: utf-8 -*-
"""Project(small images classification).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHd6huuUys5OBBvJ66l79SXH5gziQErG
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importing the libraries"""

import tensorflow as tf
from tensorflow import keras#its used to import the inbuilt Data set

"""Deeplearning Libraries

Importing the Dataset
"""

data=keras.datasets.cifar10

data

df=data.load_data()

(x_train,y_train),(x_test,y_test)=df

x_train.shape

x_test.shape

x_train[5]#to see a single image in the form of pixel

plt.matshow(x_train[5])#all the different numbers represents the different shades

for i in range(10):
  plt.matshow(x_train[i])

y_test.shape

y_test.ndim #to know the dimension

y_train.ndim

x_test.ndim

x_train.ndim

x_train_flat=x_train.reshape(len(x_train),32*32*3)
x_test_flat=x_test.reshape(len(x_test),32*32*3)
y_train_flat=y_train.reshape(len(y_train),1)
y_test_flat=y_test.reshape(len(y_test),1)

x_train_flat[0].ndim

"""ANN Model creation"""

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model=Sequential([
                  Dense(units=10,
                        input_shape=(3072,),
                        activation='relu')
])
model.compile(
    optimizer='adam',
    loss = 'SparseCategoricalCrossentropy',
    metrics=['accuracy']
)

"""Training/Fit the model"""

model.fit(x_train_flat,y_train_flat,epochs=10)

y_pred = model.predict(x_test_flat)

y_pred

model.evaluate(x_test_flat,y_test_flat)

